### ISSUE TITLE
Not breaking text into pages

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paging#10]
I am experimenting with this module and it's generating the pager, but it is not breaking the text up into different pages, rather all of the text shows up on all of the pages. 

Steps To Recreate:

1) Started with a fresh site and enabled the paging module.
2) Enabled the module for "Page" content type, selected the body field, and set it to break every 500 characters. 
3) Copied a very [long bit of text](http://catdir.loc.gov/catdir/enhancements/fy0711/2006051179-s.html) into the body field of a test "Page."
4) Save node and observe that a pager is present on node, but all of the content shows up on every page. 

I only expect to see 500 characters per page. I also tried limiting to words per page or inserting . In every case the pager works, but all of the content is on every page. 

![Page___Paging](https://user-images.githubusercontent.com/3144571/62408499-a4b84000-b58f-11e9-9268-f3fdf0c71d15.png)

![Test_Story_-_Page_4___Paging](https://user-images.githubusercontent.com/3144571/62408510-d3361b00-b58f-11e9-8a10-0cea4623208a.png)

**Comment by jenlampton** [comment]
I believe I found the issue that was causing this problem, we were not pulling the specific field used for each node type properly, so were then unable to count pages based on that field. I've pushed a fix for that. Please re-open if anyone else encounters this issue again.
