### ISSUE TITLE
[UX] Ignore hidden required fields

### ISSUE THREAD

**Issue by kthull** [backdrop-contrib/paging#9]
With paging module enabled, when creating a new content type, you will receive the following errors until you errors if you don't enable paging for the new content type:

`Automatic paging field is required.
Number of characters to display per page field is required.
Minumum character length for final page field is required.
Number of words to display per page field is required.
Minumum word length for final page field is required.`

Plus `Limit by characters (recommended)` and `Limit by words` radio buttons must be toggled in order to reveal their hidden required fields.

**Comment by jenlampton** [comment]
The fields have been given appropriate default values, and are no longer required. We still need to do some work on the UX, but this initial problem has been resolved.
